configuration_folder="configuration_ResNet50V2"
nohup python3 main.py --configuration=./$configuration_folder/Resnet50V2_RGBD_128_batch_10h_training_5h_validation_weather_prelu_speed_conv1_augmentation_weak_steer_brake_speed_factor.json > Resnet50V2_RGBD_128_batch_10h_training_5h_validation_weather_prelu_speed_conv1_augmentation_weak_steer_brake_speed_factor.txt &

